In [3]:
import pandas as pd
import numpy as np

df=pd.read_excel('C:\\articles\\to_upload\\Vizcarra\\ZonalSt_Int_unmasked_TableToExcel.xls')
#C:\articles\to_upload\Vizcarra
print(df)


X_raw = (df["S2_NDVI"].to_numpy())
#print(X_raw.shape)
X=np.reshape(X_raw,(X_raw.shape[0], 1))
y=(df["MEAN_drone"].to_numpy()).ravel()

#y=np.atleast_2d(y)

print(X.shape,y.shape)

#X_train= X[500:1500]
#Y_train= y[500:1500]

#X_test=X[1500:2000]
#Y_test=y[1500:2000]
#print(X_train.shape, Y_train.shape, X_test.shape,Y_test.shape)




      OBJECTID   S2_NDVI   VALUE  COUNT        AREA  MIN_drone  MAX_drone  \
0            1  0.564864  564864   2477   54.395604   0.430298   0.927538   
1            2  0.640211  640211   2773   60.895846   0.531558   0.935376   
2            3  0.645990  645990   3103   68.142737   0.203673   0.938252   
3            4  0.648998  648998   3487   76.575483   0.611573   0.958789   
4            5  0.600625  600625   3768   82.746320   0.288474   0.933030   
...        ...       ...     ...    ...         ...        ...        ...   
3936      3937  0.131985  131985   4556  100.051018   0.094310   0.526329   
3937      3938  0.154743  154743   4624  101.544317   0.105027   0.538654   
3938      3939  0.158506  158506   4311   94.670750   0.122084   0.281722   
3939      3940  0.168395  168395   3041   66.781200   0.104063   0.310620   
3940      3941  0.156135  156135   2424   53.231709   0.091932   0.531313   

         RANGE  MEAN_drone       STD          SUM  
0     0.497241    0.821

In [9]:
# Install scikit-learn using conda or pip if you don't already have it installed
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

# Generate some synthetic data
#X, y = make_regression()

# Split the synthetic data into train and test arrays
X_train, X_test, Y_train, Y_test = train_test_split(X, y)

# The number of trees is set by n_estimators; there are many other options that
# you should experiment with. Typically the defaults will be sensible but are
# unlikely to be perfect for your use case. Let's create the empty model:
r_squaredvalues=[]

for n_estimators in (100,200,300,400,500):
    
    reg = GradientBoostingRegressor(n_estimators=n_estimators,
                                max_depth=3,
                                learning_rate=0.1,
                                min_samples_split=3)
    # Fit the model
    reg.fit(X_train, Y_train)

    # Predict the value of the first test case
    #reg.predict(X_test[:1])

    # R^2 score for the model (on the test data)
    r_squaredvalues.append((n_estimators, reg.score(X_test, Y_test)))

In [10]:
r_squaredvalues

[(100, 0.7395229189306506),
 (200, 0.7349403781822135),
 (300, 0.7251354030082064),
 (400, 0.7197718432251008),
 (500, 0.7151571890734552)]

In [5]:
Y_test= reg.predict(X_test)

In [5]:
X_test.shape

(986, 1)

In [6]:
reg.score(X_test, Y_test)

1.0

In [7]:
import joblib

# save
joblib.dump(reg, "boostedRegressionNDVI.jl") 

# load
reg = joblib.load("boostedRegressionNDVI.jl")

#clf2.predict(X[0:1])

In [40]:
reg.predict((np.array(0.5)).reshape(1,-1))

array([0.70621557])

In [9]:
from numpy import genfromtxt
my_data = genfromtxt('C:\\Users\\karm_ch\\Downloads\\s2_ndvi_all_sampling_zones.csv', delimiter=';')

In [10]:
my_data[0]

array([nan, nan, nan, nan, nan, nan])

In [11]:
my_data[1]

array([           nan, 4.29765000e+05, 2.10575655e-01,            nan,
                  nan,            nan])

In [17]:
import csv
ndvi=[]
with open('C:\\Users\\karm_ch\\Downloads\\s2_ndvi_all_sampling_zones.csv', newline='') as pscfile:
    reader = csv.DictReader(pscfile)
    for row in reader:
        print(row)
        ndvi.append(row)
    

{'lattitude': '4619035.000000000000000', 'logitude': '429764.999999999941792', 'uncorrected_ndvi': '0.210575655102730', 'id': 'PR034', 'CLEARING': 'YES', 'parcel_id': 'PR03'}
{'lattitude': '4618875.000000000000000', 'logitude': '429804.999999999941792', 'uncorrected_ndvi': '0.178003951907158', 'id': 'PR035', 'CLEARING': 'YES', 'parcel_id': 'PR03'}
{'lattitude': '4618845.000000000000000', 'logitude': '429824.999999999941792', 'uncorrected_ndvi': '0.262857139110565', 'id': 'PR036', 'CLEARING': 'YES', 'parcel_id': 'PR03'}
{'lattitude': '4618705.000000000000000', 'logitude': '429824.999999999941792', 'uncorrected_ndvi': '0.191737055778503', 'id': 'PR031', 'CLEARING': 'NO', 'parcel_id': 'PR03'}
{'lattitude': '4618675.000000000000000', 'logitude': '429835.000000000058208', 'uncorrected_ndvi': '0.218301698565483', 'id': 'PR032', 'CLEARING': 'NO', 'parcel_id': 'PR03'}
{'lattitude': '4618645.000000000000000', 'logitude': '429844.999999999941792', 'uncorrected_ndvi': '0.257296472787857', 'id': '

In [29]:
len(ndvi[0])

6

In [42]:
for i in range(len(ndvi)):
    #print(ndvi[i])
    for j in range (len(ndvi[i])):
        print(ndvi[i]["id"])
        val = ndvi[i]["uncorrected_ndvi"]
        newval=reg.predict((np.array(val)).reshape(1,-1))
        ndvi[i]["corrected_ndvi"]=newval
    

PR034
PR034
PR034
PR034
PR034
PR034
PR035
PR035
PR035
PR035
PR035
PR035
PR036
PR036
PR036
PR036
PR036
PR036
PR031
PR031
PR031
PR031
PR031
PR031
PR032
PR032
PR032
PR032
PR032
PR032
PR033
PR033
PR033
PR033
PR033
PR033
PR013
PR013
PR013
PR013
PR013
PR013
PR012
PR012
PR012
PR012
PR012
PR012
PR011
PR011
PR011
PR011
PR011
PR011
PR014
PR014
PR014
PR014
PR014
PR014
PR016
PR016
PR016
PR016
PR016
PR016
PR015
PR015
PR015
PR015
PR015
PR015
VZ031
VZ031
VZ031
VZ031
VZ031
VZ031
VZ032
VZ032
VZ032
VZ032
VZ032
VZ032
VZ036
VZ036
VZ036
VZ036
VZ036
VZ036
VZ034
VZ034
VZ034
VZ034
VZ034
VZ034
VZ035
VZ035
VZ035
VZ035
VZ035
VZ035
PR024
PR024
PR024
PR024
PR024
PR024
PR022
PR022
PR022
PR022
PR022
PR022
PR021
PR021
PR021
PR021
PR021
PR021
PR025
PR025
PR025
PR025
PR025
PR025
PR023
PR023
PR023
PR023
PR023
PR023
PR026
PR026
PR026
PR026
PR026
PR026
VZ011
VZ011
VZ011
VZ011
VZ011
VZ011
VZ012
VZ012
VZ012
VZ012
VZ012
VZ012
VZ015
VZ015
VZ015
VZ015
VZ015
VZ015
VZ013
VZ013
VZ013
VZ013
VZ013
VZ013
VZ016
VZ016
VZ016
VZ016
VZ01

In [44]:
import pandas as pd
data=pd.DataFrame(ndvi)

In [46]:
data.to_excel("ndvi_all_sampling_zones_ai4eu.xlsx") 